### ISSUE TITLE
How would I go by building Data's branch?

### ISSUE THREAD

**Issue by oofiewav** [DuskieWhy/NightmareVision#13]
### What is your question?

Whenever I try to build It; I get 1 singular error about MusicBeatState having an unexpected "."
![image](https://github.com/user-attachments/assets/0c2b2260-606f-4d61-a6cb-c8006a116988)

Would I have to like update one of my libraries; update haxe to be a newer version (since I just have 4.2.5 due to being unsure) or

**Comment by moxie-coder** [comment]
> ### What is your question?
> Whenever I try to build It; I get 1 singular error about MusicBeatState having an unexpected "." ![image](https://private-user-images.githubusercontent.com/143152154/366636773-0c2b2260-606f-4d61-a6cb-c8006a116988.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwOTMzNzUsIm5iZiI6MTcyNjA5MzA3NSwicGF0aCI6Ii8xNDMxNTIxNTQvMzY2NjM2NzczLTBjMmIyMjYwLTYwNmYtNGQ2MS1hNmNiLWM4MDA2YTExNjk4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQyMjE3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmU4YTJhZGFjODEzODhkM2MzOTAwOTkzMTZkZTA5ODM3YzA1ZjMzYWEwMmFhMmUzNzc5NTA0YzA3YjgyZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._FiziUiSRliPaHdluSLy_CuAQyZvOkQXrYOUYayJQH0)
> 
> Would I have to like update one of my libraries; update haxe to be a newer version (since I just have 4.2.5 due to being unsure) or

you should probably try using Haxe 4.3 since this engine is known to use that

**Comment by Piejpg** [comment]
alrighty i'll try

**Comment by Piejpg** [comment]
I used 4.3 and uh

`source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : Type not found : hxvlc.util.OneOfThree
                                                                                                               source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : ... For function argument 'child'
                                                                                                 export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
                                                                         source/Main.hx:112: characters 93-100 : flixel.FlxCamera has no field filters (Suggestion: _filters)
                                                     export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
                             source/funkin/objects/video/FunkinVideoSprite.hx:14: characters 33-50 : Type not found : hxvlc.util.Handle
               source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : Float should be Int
                                                                                                          source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : ... For optional function argument 'x'
                                                                                                source/funkin/huds/BaseHUD.hx:4: characters 8-33 : Type not found : flixel.group.FlxContainer
                                                                     source/funkin/backend/SoundGroup.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound
                                            source/funkin/backend/SoundGroup.hx:131: characters 45-66 : Type not found : flixel.sound.FlxSound
                      source/funkin/huds/BaseHUD.hx:8: characters 23-50 : Type not found : FlxTypedContainer
                                                                                                            source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method set_opponentVolume required by property opponentVolume is missing
                                                                                                                       source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method get_opponentVolume required by property opponentVolume is missing
          source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method set_playerVolume required by property playerVolume is missing
                 source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method get_playerVolume required by property playerVolume is missing
                        source/funkin/objects/video/FunkinVideoSprite.hx:102: characters 13-22 : Unknown identifier : autoPause
       source/funkin/objects/video/FunkinVideoSprite.hx:111: characters 13-22 : Unknown identifier : autoPause
                                                                                                              source/funkin/objects/video/FunkinVideoSprite.hx:20: lines 20-27 : Missing super constructor call
                                                                                       source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : () -> funkin.backend.MusicBeatState should be flixel.FlxState
                                                                                                       source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : ... For function argument 'nextState'
                                                                                               source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState
                                                                                                           source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : ... For function argument 'nextState'
                                                                                                 source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState
                                                                                                          source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : ... For function argument 'nextState'
                                                                                             source/funkin/states/PlayState.hx:2866: characters 21-34 : funkin.huds.BaseHUD has no field onUpdateScore
                                                                              source/funkin/states/PlayState.hx:192: characters 20-34 : funkin.huds.BaseHUD has no field onHealthChange
                                                               source/funkin/data/scripts/FunkinIris.hx:176: characters 25-46 : Type not found : flixel.sound.FlxSound
                                              source/funkin/data/scripts/FunkinIris.hx:178: characters 33-71 : Type not found : flixel.addons.display.FlxRuntimeShader
                                              source/funkin/data/scripts/FunkinIris.hx:240: characters 16-54 : Type not found : flixel.addons.display.FlxRuntimeShader
                                              source/funkin/data/scripts/FunkinIris.hx:244: characters 19-57 : Type not found : flixel.addons.display.FlxRuntimeShader
                                              source/funkin/data/scripts/FunkinIris.hx:254: characters 26-64 : Type not found : flixel.addons.display.FlxRuntimeShader
                                              source/funkin/states/PlayState.hx:3009: characters 20-37 : funkin.huds.BaseHUD has no field onCharacterChange
                                   source/funkin/states/PlayState.hx:4002: characters 4-27 : Could not resolve accessor
                                                                                                                       source/funkin/states/PlayState.hx:4009: characters 3-26 : Could not resolve accessor
                                                                                   source/funkin/states/PlayState.hx:3626: characters 3-26 : Could not resolve accessor
                                               source/funkin/states/PlayState.hx:4345: characters 4-27 : Could not resolve accessor
           source/funkin/states/PlayState.hx:4164: characters 4-29 : Could not resolve accessor
                                                                                               source/funkin/states/PlayState.hx:3514: characters 23-47 : () -> funkin.states.StoryMenuState should be flixel.FlxState
                                                                                              source/funkin/states/PlayState.hx:3514: characters 23-47 : ... For function argument 'nextState'
                                                                      source/funkin/states/PlayState.hx:3573: characters 22-45 : () -> funkin.states.FreeplayState should be flixel.FlxState
                                                                    source/funkin/states/PlayState.hx:3573: characters 22-45 : ... For function argument 'nextState'
                                            source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : () -> funkin.backend.MusicBeatState should be flixel.FlxState
                                                  source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : ... For function argument 'nextState'
                                source/funkin/states/transitions/FadeTransition.hx:40: characters 18-34 : Unknown identifier : getCamerasLegacy
                       source/funkin/utils/CameraUtil.hx:34: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                          source/funkin/utils/CameraUtil.hx:34: characters 44-51 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                             source/funkin/utils/CameraUtil.hx:35: characters 16-23 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                                source/funkin/utils/CameraUtil.hx:41: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                                   source/funkin/utils/CameraUtil.hx:43: characters 26-33 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                                      source/funkin/utils/CameraUtil.hx:43: characters 19-33 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
                                                source/funkin/utils/CameraUtil.hx:46: characters 54-61 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters)
                                                   source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : () -> funkin.data.options.OptionsState should be flixel.FlxState
                                                                   source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : ... For function argument 'nextState'
                                                        source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : () -> funkin.backend.MusicBeatState should be flixel.FlxState
                                                                     source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : ... For function argument 'nextState'
                                                          source/funkin/huds/PsychHUD.hx:10: lines 10-197 : Loop in class building prevent compiler termination (funkin.huds.BaseHUD)
                                                             source/funkin/states/PlayState.hx:716: characters 7-14 : funkin.huds.BaseHUD should be flixel.FlxBasic
                                           source/funkin/states/PlayState.hx:716: characters 7-14 : ... For function argument 'Object'
              source/funkin/states/PlayState.hx:717: characters 11-18 : funkin.huds.BaseHUD has no field cameras
                                                                                                                source/funkin/states/PlayState.hx:1775: characters 11-26 : funkin.backend.VocalGroup has no field addPlayerVocals (Suggestion: playerVocals)
            source/funkin/states/PlayState.hx:1780: characters 12-29 : funkin.backend.VocalGroup has no field addOpponentVocals (Suggestion: opponentVocals)
                                    source/funkin/states/PlayState.hx:4061: characters 5-28 : Could not resolve accessor                                                                                                                       source/funkin/states/PlayState.hx:4094: characters 4-27 : Could not resolve accessor
                                                                                   source/funkin/states/PlayState.hx:1676: characters 22-33 : funkin.huds.BaseHUD has no field onSongStart
                                                                  source/funkin/states/PlayState.hx:4481: characters 20-27 : funkin.huds.BaseHUD has no field stepHit
                                             source/funkin/states/PlayState.hx:4526: characters 20-27 : funkin.huds.BaseHUD has no field beatHit
                        source/funkin/states/PlayState.hx:4566: characters 20-30 : funkin.huds.BaseHUD has no field sectionHit
      source/funkin/backend/MusicBeatState.hx:164: characters 9-19 : flixel.addons.ui.FlxUIState has no field startOutro                                                                                                                       source/funkin/backend/MusicBeatState.hx:158: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field
             source/funkin/objects/video/FunkinVideoSprite.hx:42: characters 7-20 : Cannot compare Void
                                                                                                       source/funkin/objects/video/FunkinVideoSprite.hx:68: characters 13-22 : Unknown identifier : autoPause
                                                                                     source/funkin/objects/video/FunkinVideoSprite.hx:74: characters 15-24 : Variables of type Void are not allowed
                                                                           source/funkin/objects/video/FunkinVideoSprite.hx:77: characters 7-24 : Cannot compare Void
                                             source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : funkin.objects.video.Location should be String
                                           source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : ... For function argument 'location'
                               source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : Field load overrides parent class with different or incomplete type
                                                  C:/HaxeToolkit/haxe/lib/hxvlc/1,2,0/source/hxvlc/flixel/FlxVideoSprite.hx:51: characters 18-22 : ... Base field is defined here
                                                         source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... error: funkin.objects.video.Location should be String
                                                                  source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... have: (String, ...) -> ...
                                                source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... want: (funkin.objects.video.Location, ...) -> ...
                                                     source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : String should be funkin.objects.video.Location
                                                    source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : ... For function argument 'location'
                                         source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : String should be funkin.objects.video.Location
                                        source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : ... For function argument 'location'
                             source/Splash.hx:18: characters 18-22 : Class<flixel.util.FlxTimer> has no field wait
                                                                                                                  source/Splash.hx:43: characters 26-71 : () -> flixel.FlxState should be flixel.FlxState
                                                                                 source/Splash.hx:43: characters 26-71 : ... For function argument 'nextState'
                                      C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)`

**Comment by moxie-coder** [comment]
> I used 4.3.6 and uh
> 
> `source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : Type not found : hxvlc.util.OneOfThree source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : ... For function argument 'child' export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here source/Main.hx:112: characters 93-100 : flixel.FlxCamera has no field filters (Suggestion: _filters) export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here source/funkin/objects/video/FunkinVideoSprite.hx:14: characters 33-50 : Type not found : hxvlc.util.Handle source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : Float should be Int source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : ... For optional function argument 'x' source/funkin/huds/BaseHUD.hx:4: characters 8-33 : Type not found : flixel.group.FlxContainer source/funkin/backend/SoundGroup.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound source/funkin/backend/SoundGroup.hx:131: characters 45-66 : Type not found : flixel.sound.FlxSound source/funkin/huds/BaseHUD.hx:8: characters 23-50 : Type not found : FlxTypedContainer source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method set_opponentVolume required by property opponentVolume is missing source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method get_opponentVolume required by property opponentVolume is missing source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method set_playerVolume required by property playerVolume is missing source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method get_playerVolume required by property playerVolume is missing source/funkin/objects/video/FunkinVideoSprite.hx:102: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:111: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:20: lines 20-27 : Missing super constructor call source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : ... For function argument 'nextState' source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : ... For function argument 'nextState' source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : ... For function argument 'nextState' source/funkin/states/PlayState.hx:2866: characters 21-34 : funkin.huds.BaseHUD has no field onUpdateScore source/funkin/states/PlayState.hx:192: characters 20-34 : funkin.huds.BaseHUD has no field onHealthChange source/funkin/data/scripts/FunkinIris.hx:176: characters 25-46 : Type not found : flixel.sound.FlxSound source/funkin/data/scripts/FunkinIris.hx:178: characters 33-71 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:240: characters 16-54 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:244: characters 19-57 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:254: characters 26-64 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/states/PlayState.hx:3009: characters 20-37 : funkin.huds.BaseHUD has no field onCharacterChange source/funkin/states/PlayState.hx:4002: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:4009: characters 3-26 : Could not resolve accessor source/funkin/states/PlayState.hx:3626: characters 3-26 : Could not resolve accessor source/funkin/states/PlayState.hx:4345: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:4164: characters 4-29 : Could not resolve accessor source/funkin/states/PlayState.hx:3514: characters 23-47 : () -> funkin.states.StoryMenuState should be flixel.FlxState source/funkin/states/PlayState.hx:3514: characters 23-47 : ... For function argument 'nextState' source/funkin/states/PlayState.hx:3573: characters 22-45 : () -> funkin.states.FreeplayState should be flixel.FlxState source/funkin/states/PlayState.hx:3573: characters 22-45 : ... For function argument 'nextState' source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : ... For function argument 'nextState' source/funkin/states/transitions/FadeTransition.hx:40: characters 18-34 : Unknown identifier : getCamerasLegacy source/funkin/utils/CameraUtil.hx:34: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:34: characters 44-51 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:35: characters 16-23 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:41: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:43: characters 26-33 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:43: characters 19-33 : You can't iterate on a Dynamic value, please specify Iterator or Iterable source/funkin/utils/CameraUtil.hx:46: characters 54-61 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : () -> funkin.data.options.OptionsState should be flixel.FlxState source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : ... For function argument 'nextState' source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : ... For function argument 'nextState' source/funkin/huds/PsychHUD.hx:10: lines 10-197 : Loop in class building prevent compiler termination (funkin.huds.BaseHUD) source/funkin/states/PlayState.hx:716: characters 7-14 : funkin.huds.BaseHUD should be flixel.FlxBasic source/funkin/states/PlayState.hx:716: characters 7-14 : ... For function argument 'Object' source/funkin/states/PlayState.hx:717: characters 11-18 : funkin.huds.BaseHUD has no field cameras source/funkin/states/PlayState.hx:1775: characters 11-26 : funkin.backend.VocalGroup has no field addPlayerVocals (Suggestion: playerVocals) source/funkin/states/PlayState.hx:1780: characters 12-29 : funkin.backend.VocalGroup has no field addOpponentVocals (Suggestion: opponentVocals) source/funkin/states/PlayState.hx:4061: characters 5-28 : Could not resolve accessor source/funkin/states/PlayState.hx:4094: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:1676: characters 22-33 : funkin.huds.BaseHUD has no field onSongStart source/funkin/states/PlayState.hx:4481: characters 20-27 : funkin.huds.BaseHUD has no field stepHit source/funkin/states/PlayState.hx:4526: characters 20-27 : funkin.huds.BaseHUD has no field beatHit source/funkin/states/PlayState.hx:4566: characters 20-30 : funkin.huds.BaseHUD has no field sectionHit source/funkin/backend/MusicBeatState.hx:164: characters 9-19 : flixel.addons.ui.FlxUIState has no field startOutro source/funkin/backend/MusicBeatState.hx:158: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field source/funkin/objects/video/FunkinVideoSprite.hx:42: characters 7-20 : Cannot compare Void source/funkin/objects/video/FunkinVideoSprite.hx:68: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:74: characters 15-24 : Variables of type Void are not allowed source/funkin/objects/video/FunkinVideoSprite.hx:77: characters 7-24 : Cannot compare Void source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : funkin.objects.video.Location should be String source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : ... For function argument 'location' source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : Field load overrides parent class with different or incomplete type C:/HaxeToolkit/haxe/lib/hxvlc/1,2,0/source/hxvlc/flixel/FlxVideoSprite.hx:51: characters 18-22 : ... Base field is defined here source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... error: funkin.objects.video.Location should be String source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... have: (String, ...) -> ... source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... want: (funkin.objects.video.Location, ...) -> ... source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : String should be funkin.objects.video.Location source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : ... For function argument 'location' source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : String should be funkin.objects.video.Location source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : ... For function argument 'location' source/Splash.hx:18: characters 18-22 : Class<flixel.util.FlxTimer> has no field wait source/Splash.hx:43: characters 26-71 : () -> flixel.FlxState should be flixel.FlxState source/Splash.hx:43: characters 26-71 : ... For function argument 'nextState' C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)`



> I used 4.3.6 and uh
> 
> `source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : Type not found : hxvlc.util.OneOfThree source/funkin/objects/video/FunkinVideoSprite.hx:173: characters 43-84 : ... For function argument 'child' export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here source/Main.hx:112: characters 93-100 : flixel.FlxCamera has no field filters (Suggestion: _filters) export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here source/funkin/objects/video/FunkinVideoSprite.hx:14: characters 33-50 : Type not found : hxvlc.util.Handle source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : Float should be Int source/funkin/objects/video/FunkinVideoSprite.hx:21: characters 15-16 : ... For optional function argument 'x' source/funkin/huds/BaseHUD.hx:4: characters 8-33 : Type not found : flixel.group.FlxContainer source/funkin/backend/SoundGroup.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound source/funkin/backend/SoundGroup.hx:131: characters 45-66 : Type not found : flixel.sound.FlxSound source/funkin/huds/BaseHUD.hx:8: characters 23-50 : Type not found : FlxTypedContainer source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method set_opponentVolume required by property opponentVolume is missing source/funkin/backend/SoundGroup.hx:122: characters 5-46 : Method get_opponentVolume required by property opponentVolume is missing source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method set_playerVolume required by property playerVolume is missing source/funkin/backend/SoundGroup.hx:120: characters 5-44 : Method get_playerVolume required by property playerVolume is missing source/funkin/objects/video/FunkinVideoSprite.hx:102: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:111: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:20: lines 20-27 : Missing super constructor call source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/states/substates/GameOverSubstate.hx:102: characters 21-92 : ... For function argument 'nextState' source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState source/funkin/states/editors/MasterEditorMenu.hx:104: characters 21-44 : ... For function argument 'nextState' source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : () -> funkin.states.MainMenuState should be flixel.FlxState source/funkin/data/options/NoteOffsetState.hx:356: characters 21-44 : ... For function argument 'nextState' source/funkin/states/PlayState.hx:2866: characters 21-34 : funkin.huds.BaseHUD has no field onUpdateScore source/funkin/states/PlayState.hx:192: characters 20-34 : funkin.huds.BaseHUD has no field onHealthChange source/funkin/data/scripts/FunkinIris.hx:176: characters 25-46 : Type not found : flixel.sound.FlxSound source/funkin/data/scripts/FunkinIris.hx:178: characters 33-71 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:240: characters 16-54 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:244: characters 19-57 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/data/scripts/FunkinIris.hx:254: characters 26-64 : Type not found : flixel.addons.display.FlxRuntimeShader source/funkin/states/PlayState.hx:3009: characters 20-37 : funkin.huds.BaseHUD has no field onCharacterChange source/funkin/states/PlayState.hx:4002: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:4009: characters 3-26 : Could not resolve accessor source/funkin/states/PlayState.hx:3626: characters 3-26 : Could not resolve accessor source/funkin/states/PlayState.hx:4345: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:4164: characters 4-29 : Could not resolve accessor source/funkin/states/PlayState.hx:3514: characters 23-47 : () -> funkin.states.StoryMenuState should be flixel.FlxState source/funkin/states/PlayState.hx:3514: characters 23-47 : ... For function argument 'nextState' source/funkin/states/PlayState.hx:3573: characters 22-45 : () -> funkin.states.FreeplayState should be flixel.FlxState source/funkin/states/PlayState.hx:3573: characters 22-45 : ... For function argument 'nextState' source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/data/scripts/FunkinLua.hx:1149: characters 21-91 : ... For function argument 'nextState' source/funkin/states/transitions/FadeTransition.hx:40: characters 18-34 : Unknown identifier : getCamerasLegacy source/funkin/utils/CameraUtil.hx:34: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:34: characters 44-51 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:35: characters 16-23 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:41: characters 20-27 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:43: characters 26-33 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/utils/CameraUtil.hx:43: characters 19-33 : You can't iterate on a Dynamic value, please specify Iterator or Iterable source/funkin/utils/CameraUtil.hx:46: characters 54-61 : Null<flixel.FlxCamera> has no field filters (Suggestion: _filters) source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : () -> funkin.data.options.OptionsState should be flixel.FlxState source/funkin/states/substates/PauseSubState.hx:242: characters 23-45 : ... For function argument 'nextState' source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : () -> funkin.backend.MusicBeatState should be flixel.FlxState source/funkin/states/substates/PauseSubState.hx:294: characters 23-94 : ... For function argument 'nextState' source/funkin/huds/PsychHUD.hx:10: lines 10-197 : Loop in class building prevent compiler termination (funkin.huds.BaseHUD) source/funkin/states/PlayState.hx:716: characters 7-14 : funkin.huds.BaseHUD should be flixel.FlxBasic source/funkin/states/PlayState.hx:716: characters 7-14 : ... For function argument 'Object' source/funkin/states/PlayState.hx:717: characters 11-18 : funkin.huds.BaseHUD has no field cameras source/funkin/states/PlayState.hx:1775: characters 11-26 : funkin.backend.VocalGroup has no field addPlayerVocals (Suggestion: playerVocals) source/funkin/states/PlayState.hx:1780: characters 12-29 : funkin.backend.VocalGroup has no field addOpponentVocals (Suggestion: opponentVocals) source/funkin/states/PlayState.hx:4061: characters 5-28 : Could not resolve accessor source/funkin/states/PlayState.hx:4094: characters 4-27 : Could not resolve accessor source/funkin/states/PlayState.hx:1676: characters 22-33 : funkin.huds.BaseHUD has no field onSongStart source/funkin/states/PlayState.hx:4481: characters 20-27 : funkin.huds.BaseHUD has no field stepHit source/funkin/states/PlayState.hx:4526: characters 20-27 : funkin.huds.BaseHUD has no field beatHit source/funkin/states/PlayState.hx:4566: characters 20-30 : funkin.huds.BaseHUD has no field sectionHit source/funkin/backend/MusicBeatState.hx:164: characters 9-19 : flixel.addons.ui.FlxUIState has no field startOutro source/funkin/backend/MusicBeatState.hx:158: characters 20-30 : Field startOutro is declared 'override' but doesn't override any field source/funkin/objects/video/FunkinVideoSprite.hx:42: characters 7-20 : Cannot compare Void source/funkin/objects/video/FunkinVideoSprite.hx:68: characters 13-22 : Unknown identifier : autoPause source/funkin/objects/video/FunkinVideoSprite.hx:74: characters 15-24 : Variables of type Void are not allowed source/funkin/objects/video/FunkinVideoSprite.hx:77: characters 7-24 : Cannot compare Void source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : funkin.objects.video.Location should be String source/funkin/objects/video/FunkinVideoSprite.hx:96: characters 22-31 : ... For function argument 'location' source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : Field load overrides parent class with different or incomplete type C:/HaxeToolkit/haxe/lib/hxvlc/1,2,0/source/hxvlc/flixel/FlxVideoSprite.hx:51: characters 18-22 : ... Base field is defined here source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... error: funkin.objects.video.Location should be String source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... have: (String, ...) -> ... source/funkin/objects/video/FunkinVideoSprite.hx:63: characters 23-27 : ... want: (funkin.objects.video.Location, ...) -> ... source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : String should be funkin.objects.video.Location source/funkin/objects/video/FunkinVideoSprite.hx:134: characters 20-29 : ... For function argument 'location' source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : String should be funkin.objects.video.Location source/funkin/objects/video/FunkinVideoSprite.hx:140: characters 20-24 : ... For function argument 'location' source/Splash.hx:18: characters 18-22 : Class<flixel.util.FlxTimer> has no field wait source/Splash.hx:43: characters 26-71 : () -> flixel.FlxState should be flixel.FlxState source/Splash.hx:43: characters 26-71 : ... For function argument 'nextState' C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)`

try running the compile.bat file in the projFiles folder

**Comment by Piejpg** [comment]
well i've been using the compile.bat file the entire time but sadly its still giving me the same error
