### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by ShygeeGit** [DuskieWhy/NightmareVision#15]
### Describe your problem here.

I've made sure i have all the right libraries and the right haxe version, no clue why its doing this

![image](https://github.com/user-attachments/assets/4d87f5c6-e9a4-4c2b-873a-db94e7021eb0)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

**Comment by moxie-coder** [comment]
did you try running the setup file?

**Comment by ShygeeGit** [comment]
i did yea, even then it still didnt work

**Comment by moxie-coder** [comment]
are you also using Haxe 4.3?

**Comment by ShygeeGit** [comment]
yep i am
