### ISSUE TITLE
Compiling Error - Lime

### ISSUE THREAD

**Issue by NotSomeBlox** [DuskieWhy/NightmareVision#33]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/b2cfef33-092f-4f46-adb9-39131e2a8a7b)

When trying to compile, it gives me this despite everything looking fine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no. simpl,y Compiling

**Comment by moxie-coder** [comment]
`haxelib install lime 8.1.2`

**Comment by NotSomeBlox** [comment]
i installed all of the libraries including lime when i first compiled

**Comment by moxie-coder** [comment]
then try `haxelib —global install lime`

**Comment by NotSomeBlox** [comment]
still shows this after putting it into the command prompt, im not sure if i need to uninstall lime to do this

**Comment by NotSomeBlox** [comment]
is there anything else that i can do to try to solve this?
